<?php
$z[0]=Array("global","",360,387);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",457,484);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",487,513);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",666,692);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>About us</span></a></li>\r\n          ",829,966);
$z[4][4]['typeid']="1";
$z[5]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Achievement</span></a></li>\r\n          ",978,1118);
$z[5][4]['typeid']="5";
$z[6]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>News</span></a></li>\r\n          ",1130,1263);
$z[6][4]['typeid']="9";
$z[7]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Knowledge</span></a></li>\r\n          ",1275,1414);
$z[7][4]['typeid']="12";
$z[8]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Services</span></a></li>\r\n          ",1426,1564);
$z[8][4]['typeid']="14";
$z[9]=Array("type","\r\n          <li><a href=\"[field:typelink/]\">[field:typename/]<span>Contact</span></a></li>\r\n          ",1576,1713);
$z[9][4]['typeid']="17";

?>