<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",763,798);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1015,1044);
$z[5][4]['name']="position";
$z[6]=Array("field","",1085,1114);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1232,1253);
$z[7][4]['name']="content";
$z[8]=Array("field","",1441,1500);
$z[8][4]['name']="typeid";
$z[8][4]['function']="GetTopTypename(@me)";
$z[9]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" >[field:typename/]</a> </li>\r\n        ",1553,1812);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li class='current'><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[10]=Array("include","",1925,1962);
$z[10][4]['filename']="footer.htm";

?>